declare type Location = {
  id: string;
  name: string;
  title:string
};
export const locations: Location[] = [
  { id: "a1g6d4c3", name:"all", title: "all" },
  { id: "a1f6d4c3", name:"CACENTRE-1", title: "CACenter01" },
  { id: "d9e7b5a2", name:"CACENTRE-2", title: "CACenter02" },
  { id: "b3c8f1d6", name:"CACENTRE-3", title: "CACenter03" },
  { id: "b3c9f1d6", name:"CACENTRE-4", title: "CACenter04" },
  { id: "728ed52f", name:"Kahawa", title: "Kahawa" },
  { id: "b94fa1c3", name:"Mombasa", title: "Mombasa" },
  { id: "c3d8a7b2", name:"Kisumu", title: "Kisumu" },
  { id: "e56f21d9", name:"Nakuru", title: "Nakuru" },
  { id: "f41a6c78", name:"South B", title: "South B" },
  { id: "9a2d5e3b", name:"Kitale", title: "Kitale" },
  { id: "3e8f7d4c", name:"Nyeri", title: "Nyeri" },
  { id: "5b6c9e1a", name:"Garissa", title: "Garissa" },
  { id: "1d2f4a8b", name:"Embu", title: "Embu" },
  { id: "7c5a9d3e", name:"Kitui", title: "Kitui" },
  { id: "8d3b1f6a", name:"Meru", title: "Meru" },
  { id: "2f7c4a9e", name:"Bungoma", title: "Bungoma" },
  { id: "6a9e5b3d", name:"Kisii", title: "Kisii" },
  { id: "4c1d8f7a", name:"Eldoret", title: "Eldoret" },
  { id: "9e3b5c7a", name:"Marsabit", title: "Marsabit" },
  { id: "9e9b5c7a", name:"Migori", title: "Migori" },
  { id: "9etb5c7a", name:"Lodwar", title: "Lodwar" },
  { id: "9e7b5c7a", name:"Kabarnet", title: "Kabarnet" },
  { id: "9e6b5c7a", name:"Malindi", title: "Malindi" },
];
export const reports = [  {
      id: "728ed52f",
      name: "Report on Channel clarity in ACTMombasa 0n 23/02/25",
      createdBy: "Raphael",
      date: new Date("2025-03-21").toLocaleDateString(),
      type: "exel",
    },
    {
      id: "489e1d42",
      name: "Report on Channel clarity in ACTNairobi 0n 23/02/25",
      createdBy: "Daniel",
      date: new Date("2025-03-21").toLocaleDateString(),
      type: "exel",
    },
    {
      id: "881f1d52",
      name: "Report on Channel clarity in CACenter01 0n 23/02/25",
      createdBy: "Daniel",
      date: new Date("2025-03-21").toLocaleDateString(),
      type: "exel",
    },
    {
      id: "175et7d2",
      name: "Report on Channel clarity in CACenter02 0n 23/02/25",
      createdBy: "Daniel",
      date: new Date("2025-03-21").toLocaleDateString(),
      type: "exel",
    },
    {
      id: "4247u6f2",
      name: "Report on Channel clarity in ACTKahawa 0n 23/02/25",
      createdBy: "Shadaai",
      date: new Date("2025-03-21").toLocaleDateString(),
      type: "pdf",
    },
    {
      id: "359v8n82",
      name: "Report on Channel clarity in ACTMuranga 0n 23/02/25",
      createdBy: "Shadaai",
      date: new Date("2025-03-21").toLocaleDateString(),
      type: "pdf",
    },
    {
      id: "962v2s43",
      name: "Report on Channel clarity in ACTNyeri 0n 23/02/25",
      createdBy: "Raphael",
      date: new Date("2025-03-21").toLocaleDateString(),
      type: "exel",
    },
  ];
